release: python manage.py migrate
web: gunicorn --workers=1 --max-requests=1000 --max-requests-jitter=50 {{ cookiecutter.project_slug }}.config.wsgi
worker: celery -A {{ cookiecutter.project_slug }}.config.celery_app worker -l INFO
