#!/usr/bin/env bash

set -euo pipefail

echo "Building assets..."
docker-compose run --rm assets yarn build-js
docker-compose run --rm assets yarn build-css

echo "Deploying assets to S3..."
docker-compose run --rm \
    -e DJANGO_SETTINGS_MODULE={{ cookiecutter.project_slug }}.config.settings.deploy \
    django ./manage.py collectstatic --noinput -v 3 -i src

echo "Deploying to Heroku..."
git push heroku master
